# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/liteDRAM.xdc

# XDC: imports/src/rvfpga.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_1 || ORIG_REF_NAME==BD_bidirec_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_2 || ORIG_REF_NAME==BD_bidirec_0_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_3/BD_bidirec_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_3 || ORIG_REF_NAME==BD_bidirec_0_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_4/BD_bidirec_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_4 || ORIG_REF_NAME==BD_bidirec_0_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_5/BD_bidirec_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_5 || ORIG_REF_NAME==BD_bidirec_0_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_0/BD_bidirec_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_0 || ORIG_REF_NAME==BD_bidirec_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_0 || ORIG_REF_NAME==BD_bidirec_2_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_0/BD_bidirec_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_0 || ORIG_REF_NAME==BD_bidirec_3_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_1/BD_bidirec_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_1 || ORIG_REF_NAME==BD_bidirec_7_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_2/BD_bidirec_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_2 || ORIG_REF_NAME==BD_bidirec_7_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_3/BD_bidirec_7_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_3 || ORIG_REF_NAME==BD_bidirec_7_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_4/BD_bidirec_7_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_4 || ORIG_REF_NAME==BD_bidirec_7_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_5/BD_bidirec_7_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_5 || ORIG_REF_NAME==BD_bidirec_7_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_6/BD_bidirec_7_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_6 || ORIG_REF_NAME==BD_bidirec_7_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_7/BD_bidirec_7_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_7 || ORIG_REF_NAME==BD_bidirec_7_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_8/BD_bidirec_7_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_8 || ORIG_REF_NAME==BD_bidirec_7_8} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_0/BD_bidirec_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_0 || ORIG_REF_NAME==BD_bidirec_16_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_1/BD_bidirec_16_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_1 || ORIG_REF_NAME==BD_bidirec_16_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_2/BD_bidirec_16_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_2 || ORIG_REF_NAME==BD_bidirec_16_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_3/BD_bidirec_16_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_3 || ORIG_REF_NAME==BD_bidirec_16_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_4/BD_bidirec_16_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_4 || ORIG_REF_NAME==BD_bidirec_16_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_17_0/BD_bidirec_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_17_0 || ORIG_REF_NAME==BD_bidirec_17_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_18_0/BD_bidirec_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_18_0 || ORIG_REF_NAME==BD_bidirec_18_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_0/BD_bidirec_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_19_0 || ORIG_REF_NAME==BD_bidirec_19_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_5/BD_bidirec_16_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_5 || ORIG_REF_NAME==BD_bidirec_16_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_17_1/BD_bidirec_17_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_17_1 || ORIG_REF_NAME==BD_bidirec_17_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_18_1/BD_bidirec_18_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_18_1 || ORIG_REF_NAME==BD_bidirec_18_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_1/BD_bidirec_19_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_19_1 || ORIG_REF_NAME==BD_bidirec_19_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_20_0/BD_bidirec_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_20_0 || ORIG_REF_NAME==BD_bidirec_20_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_21_0/BD_bidirec_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_21_0 || ORIG_REF_NAME==BD_bidirec_21_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_22_0/BD_bidirec_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_22_0 || ORIG_REF_NAME==BD_bidirec_22_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_23_0/BD_bidirec_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_23_0 || ORIG_REF_NAME==BD_bidirec_23_0} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
