-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Fri Mar 21 14:51:37 2025
-- Host        : ayman-t480 running 64-bit Ubuntu 24.10
-- Command     : write_vhdl -force -mode synth_stub
--               /home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabProjects/Lab1/Lab1.gen/sources_1/bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0_stub.vhdl
-- Design      : BD_swerv_wrapper_verilog_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7a100tcsg324-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity BD_swerv_wrapper_verilog_0_0 is
  Port ( 
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    nmi_int : in STD_LOGIC;
    nmi_vec : in STD_LOGIC_VECTOR ( 31 downto 0 );
    lsu_axi_awvalid : out STD_LOGIC;
    lsu_axi_awready : in STD_LOGIC;
    lsu_axi_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    lsu_axi_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    lsu_axi_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    lsu_axi_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    lsu_axi_awlock : out STD_LOGIC;
    lsu_axi_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    lsu_axi_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_wvalid : out STD_LOGIC;
    lsu_axi_wready : in STD_LOGIC;
    lsu_axi_wdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    lsu_axi_wstrb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    lsu_axi_wlast : out STD_LOGIC;
    lsu_axi_bvalid : in STD_LOGIC;
    lsu_axi_bready : out STD_LOGIC;
    lsu_axi_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    lsu_axi_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_arvalid : out STD_LOGIC;
    lsu_axi_arready : in STD_LOGIC;
    lsu_axi_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    lsu_axi_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    lsu_axi_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    lsu_axi_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    lsu_axi_arlock : out STD_LOGIC;
    lsu_axi_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    lsu_axi_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_rvalid : in STD_LOGIC;
    lsu_axi_rready : out STD_LOGIC;
    lsu_axi_rid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    lsu_axi_rdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    lsu_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    lsu_axi_rlast : in STD_LOGIC;
    ifu_axi_arvalid : out STD_LOGIC;
    ifu_axi_arready : in STD_LOGIC;
    ifu_axi_arid : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ifu_axi_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ifu_axi_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ifu_axi_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ifu_axi_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ifu_axi_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ifu_axi_arlock : out STD_LOGIC;
    ifu_axi_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ifu_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ifu_axi_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ifu_axi_rvalid : in STD_LOGIC;
    ifu_axi_rready : out STD_LOGIC;
    ifu_axi_rid : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ifu_axi_rdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    ifu_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ifu_axi_rlast : in STD_LOGIC;
    sb_axi_awvalid : out STD_LOGIC;
    sb_axi_awready : in STD_LOGIC;
    sb_axi_awid : out STD_LOGIC_VECTOR ( 0 to 0 );
    sb_axi_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    sb_axi_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    sb_axi_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    sb_axi_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    sb_axi_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    sb_axi_awlock : out STD_LOGIC;
    sb_axi_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    sb_axi_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    sb_axi_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    sb_axi_wvalid : out STD_LOGIC;
    sb_axi_wready : in STD_LOGIC;
    sb_axi_wdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    sb_axi_wstrb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    sb_axi_wlast : out STD_LOGIC;
    sb_axi_bvalid : in STD_LOGIC;
    sb_axi_bready : out STD_LOGIC;
    sb_axi_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    sb_axi_bid : in STD_LOGIC_VECTOR ( 0 to 0 );
    sb_axi_arvalid : out STD_LOGIC;
    sb_axi_arready : in STD_LOGIC;
    sb_axi_arid : out STD_LOGIC_VECTOR ( 0 to 0 );
    sb_axi_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    sb_axi_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    sb_axi_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    sb_axi_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    sb_axi_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    sb_axi_arlock : out STD_LOGIC;
    sb_axi_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    sb_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    sb_axi_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    sb_axi_rvalid : in STD_LOGIC;
    sb_axi_rready : out STD_LOGIC;
    sb_axi_rid : in STD_LOGIC_VECTOR ( 0 to 0 );
    sb_axi_rdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    sb_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    sb_axi_rlast : in STD_LOGIC;
    timer_int : in STD_LOGIC;
    dmi_reg_en : in STD_LOGIC;
    dmi_reg_addr : in STD_LOGIC_VECTOR ( 6 downto 0 );
    dmi_reg_wr_en : in STD_LOGIC;
    dmi_reg_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    dmi_reg_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    dmi_hard_reset : in STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of BD_swerv_wrapper_verilog_0_0 : entity is "BD_swerv_wrapper_verilog_0_0,swerv_wrapper_verilog,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of BD_swerv_wrapper_verilog_0_0 : entity is "BD_swerv_wrapper_verilog_0_0,swerv_wrapper_verilog,{x_ipProduct=Vivado 2024.2,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=swerv_wrapper_verilog,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of BD_swerv_wrapper_verilog_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of BD_swerv_wrapper_verilog_0_0 : entity is "module_ref";
end BD_swerv_wrapper_verilog_0_0;

architecture stub of BD_swerv_wrapper_verilog_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "clk,rst,nmi_int,nmi_vec[31:0],lsu_axi_awvalid,lsu_axi_awready,lsu_axi_awid[3:0],lsu_axi_awaddr[31:0],lsu_axi_awregion[3:0],lsu_axi_awlen[7:0],lsu_axi_awsize[2:0],lsu_axi_awburst[1:0],lsu_axi_awlock,lsu_axi_awcache[3:0],lsu_axi_awprot[2:0],lsu_axi_awqos[3:0],lsu_axi_wvalid,lsu_axi_wready,lsu_axi_wdata[63:0],lsu_axi_wstrb[7:0],lsu_axi_wlast,lsu_axi_bvalid,lsu_axi_bready,lsu_axi_bresp[1:0],lsu_axi_bid[3:0],lsu_axi_arvalid,lsu_axi_arready,lsu_axi_arid[3:0],lsu_axi_araddr[31:0],lsu_axi_arregion[3:0],lsu_axi_arlen[7:0],lsu_axi_arsize[2:0],lsu_axi_arburst[1:0],lsu_axi_arlock,lsu_axi_arcache[3:0],lsu_axi_arprot[2:0],lsu_axi_arqos[3:0],lsu_axi_rvalid,lsu_axi_rready,lsu_axi_rid[3:0],lsu_axi_rdata[63:0],lsu_axi_rresp[1:0],lsu_axi_rlast,ifu_axi_arvalid,ifu_axi_arready,ifu_axi_arid[2:0],ifu_axi_araddr[31:0],ifu_axi_arregion[3:0],ifu_axi_arlen[7:0],ifu_axi_arsize[2:0],ifu_axi_arburst[1:0],ifu_axi_arlock,ifu_axi_arcache[3:0],ifu_axi_arprot[2:0],ifu_axi_arqos[3:0],ifu_axi_rvalid,ifu_axi_rready,ifu_axi_rid[2:0],ifu_axi_rdata[63:0],ifu_axi_rresp[1:0],ifu_axi_rlast,sb_axi_awvalid,sb_axi_awready,sb_axi_awid[0:0],sb_axi_awaddr[31:0],sb_axi_awregion[3:0],sb_axi_awlen[7:0],sb_axi_awsize[2:0],sb_axi_awburst[1:0],sb_axi_awlock,sb_axi_awcache[3:0],sb_axi_awprot[2:0],sb_axi_awqos[3:0],sb_axi_wvalid,sb_axi_wready,sb_axi_wdata[63:0],sb_axi_wstrb[7:0],sb_axi_wlast,sb_axi_bvalid,sb_axi_bready,sb_axi_bresp[1:0],sb_axi_bid[0:0],sb_axi_arvalid,sb_axi_arready,sb_axi_arid[0:0],sb_axi_araddr[31:0],sb_axi_arregion[3:0],sb_axi_arlen[7:0],sb_axi_arsize[2:0],sb_axi_arburst[1:0],sb_axi_arlock,sb_axi_arcache[3:0],sb_axi_arprot[2:0],sb_axi_arqos[3:0],sb_axi_rvalid,sb_axi_rready,sb_axi_rid[0:0],sb_axi_rdata[63:0],sb_axi_rresp[1:0],sb_axi_rlast,timer_int,dmi_reg_en,dmi_reg_addr[6:0],dmi_reg_wr_en,dmi_reg_wdata[31:0],dmi_reg_rdata[31:0],dmi_hard_reset";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of clk : signal is "xilinx.com:signal:clock:1.0 clk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of clk : signal is "XIL_INTERFACENAME clk, ASSOCIATED_BUSIF ifu_axi:lsu_axi:sb_axi, ASSOCIATED_RESET rst, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN BD_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rst : signal is "xilinx.com:signal:reset:1.0 rst RST";
  attribute X_INTERFACE_MODE of rst : signal is "slave";
  attribute X_INTERFACE_PARAMETER of rst : signal is "XIL_INTERFACENAME rst, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of lsu_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWVALID";
  attribute X_INTERFACE_MODE of lsu_axi_awvalid : signal is "master";
  attribute X_INTERFACE_PARAMETER of lsu_axi_awvalid : signal is "XIL_INTERFACENAME lsu_axi, DATA_WIDTH 64, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN BD_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of lsu_axi_awready : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWREADY";
  attribute X_INTERFACE_INFO of lsu_axi_awid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWID";
  attribute X_INTERFACE_INFO of lsu_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWADDR";
  attribute X_INTERFACE_INFO of lsu_axi_awregion : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWREGION";
  attribute X_INTERFACE_INFO of lsu_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWLEN";
  attribute X_INTERFACE_INFO of lsu_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWSIZE";
  attribute X_INTERFACE_INFO of lsu_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWBURST";
  attribute X_INTERFACE_INFO of lsu_axi_awlock : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWLOCK";
  attribute X_INTERFACE_INFO of lsu_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWCACHE";
  attribute X_INTERFACE_INFO of lsu_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWPROT";
  attribute X_INTERFACE_INFO of lsu_axi_awqos : signal is "xilinx.com:interface:aximm:1.0 lsu_axi AWQOS";
  attribute X_INTERFACE_INFO of lsu_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi WVALID";
  attribute X_INTERFACE_INFO of lsu_axi_wready : signal is "xilinx.com:interface:aximm:1.0 lsu_axi WREADY";
  attribute X_INTERFACE_INFO of lsu_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 lsu_axi WDATA";
  attribute X_INTERFACE_INFO of lsu_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 lsu_axi WSTRB";
  attribute X_INTERFACE_INFO of lsu_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 lsu_axi WLAST";
  attribute X_INTERFACE_INFO of lsu_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi BVALID";
  attribute X_INTERFACE_INFO of lsu_axi_bready : signal is "xilinx.com:interface:aximm:1.0 lsu_axi BREADY";
  attribute X_INTERFACE_INFO of lsu_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 lsu_axi BRESP";
  attribute X_INTERFACE_INFO of lsu_axi_bid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi BID";
  attribute X_INTERFACE_INFO of lsu_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARVALID";
  attribute X_INTERFACE_INFO of lsu_axi_arready : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARREADY";
  attribute X_INTERFACE_INFO of lsu_axi_arid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARID";
  attribute X_INTERFACE_INFO of lsu_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARADDR";
  attribute X_INTERFACE_INFO of lsu_axi_arregion : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARREGION";
  attribute X_INTERFACE_INFO of lsu_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARLEN";
  attribute X_INTERFACE_INFO of lsu_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARSIZE";
  attribute X_INTERFACE_INFO of lsu_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARBURST";
  attribute X_INTERFACE_INFO of lsu_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARLOCK";
  attribute X_INTERFACE_INFO of lsu_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARCACHE";
  attribute X_INTERFACE_INFO of lsu_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARPROT";
  attribute X_INTERFACE_INFO of lsu_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 lsu_axi ARQOS";
  attribute X_INTERFACE_INFO of lsu_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi RVALID";
  attribute X_INTERFACE_INFO of lsu_axi_rready : signal is "xilinx.com:interface:aximm:1.0 lsu_axi RREADY";
  attribute X_INTERFACE_INFO of lsu_axi_rid : signal is "xilinx.com:interface:aximm:1.0 lsu_axi RID";
  attribute X_INTERFACE_INFO of lsu_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 lsu_axi RDATA";
  attribute X_INTERFACE_INFO of lsu_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 lsu_axi RRESP";
  attribute X_INTERFACE_INFO of lsu_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 lsu_axi RLAST";
  attribute X_INTERFACE_INFO of ifu_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARVALID";
  attribute X_INTERFACE_MODE of ifu_axi_arvalid : signal is "master";
  attribute X_INTERFACE_PARAMETER of ifu_axi_arvalid : signal is "XIL_INTERFACENAME ifu_axi, DATA_WIDTH 64, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 3, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN BD_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ifu_axi_arready : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARREADY";
  attribute X_INTERFACE_INFO of ifu_axi_arid : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARID";
  attribute X_INTERFACE_INFO of ifu_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARADDR";
  attribute X_INTERFACE_INFO of ifu_axi_arregion : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARREGION";
  attribute X_INTERFACE_INFO of ifu_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARLEN";
  attribute X_INTERFACE_INFO of ifu_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARSIZE";
  attribute X_INTERFACE_INFO of ifu_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARBURST";
  attribute X_INTERFACE_INFO of ifu_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARLOCK";
  attribute X_INTERFACE_INFO of ifu_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARCACHE";
  attribute X_INTERFACE_INFO of ifu_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARPROT";
  attribute X_INTERFACE_INFO of ifu_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 ifu_axi ARQOS";
  attribute X_INTERFACE_INFO of ifu_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 ifu_axi RVALID";
  attribute X_INTERFACE_INFO of ifu_axi_rready : signal is "xilinx.com:interface:aximm:1.0 ifu_axi RREADY";
  attribute X_INTERFACE_INFO of ifu_axi_rid : signal is "xilinx.com:interface:aximm:1.0 ifu_axi RID";
  attribute X_INTERFACE_INFO of ifu_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 ifu_axi RDATA";
  attribute X_INTERFACE_INFO of ifu_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 ifu_axi RRESP";
  attribute X_INTERFACE_INFO of ifu_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 ifu_axi RLAST";
  attribute X_INTERFACE_INFO of sb_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWVALID";
  attribute X_INTERFACE_MODE of sb_axi_awvalid : signal is "master";
  attribute X_INTERFACE_PARAMETER of sb_axi_awvalid : signal is "XIL_INTERFACENAME sb_axi, DATA_WIDTH 64, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 1, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN BD_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of sb_axi_awready : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWREADY";
  attribute X_INTERFACE_INFO of sb_axi_awid : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWID";
  attribute X_INTERFACE_INFO of sb_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWADDR";
  attribute X_INTERFACE_INFO of sb_axi_awregion : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWREGION";
  attribute X_INTERFACE_INFO of sb_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWLEN";
  attribute X_INTERFACE_INFO of sb_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWSIZE";
  attribute X_INTERFACE_INFO of sb_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWBURST";
  attribute X_INTERFACE_INFO of sb_axi_awlock : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWLOCK";
  attribute X_INTERFACE_INFO of sb_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWCACHE";
  attribute X_INTERFACE_INFO of sb_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWPROT";
  attribute X_INTERFACE_INFO of sb_axi_awqos : signal is "xilinx.com:interface:aximm:1.0 sb_axi AWQOS";
  attribute X_INTERFACE_INFO of sb_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 sb_axi WVALID";
  attribute X_INTERFACE_INFO of sb_axi_wready : signal is "xilinx.com:interface:aximm:1.0 sb_axi WREADY";
  attribute X_INTERFACE_INFO of sb_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 sb_axi WDATA";
  attribute X_INTERFACE_INFO of sb_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 sb_axi WSTRB";
  attribute X_INTERFACE_INFO of sb_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 sb_axi WLAST";
  attribute X_INTERFACE_INFO of sb_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 sb_axi BVALID";
  attribute X_INTERFACE_INFO of sb_axi_bready : signal is "xilinx.com:interface:aximm:1.0 sb_axi BREADY";
  attribute X_INTERFACE_INFO of sb_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 sb_axi BRESP";
  attribute X_INTERFACE_INFO of sb_axi_bid : signal is "xilinx.com:interface:aximm:1.0 sb_axi BID";
  attribute X_INTERFACE_INFO of sb_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARVALID";
  attribute X_INTERFACE_INFO of sb_axi_arready : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARREADY";
  attribute X_INTERFACE_INFO of sb_axi_arid : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARID";
  attribute X_INTERFACE_INFO of sb_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARADDR";
  attribute X_INTERFACE_INFO of sb_axi_arregion : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARREGION";
  attribute X_INTERFACE_INFO of sb_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARLEN";
  attribute X_INTERFACE_INFO of sb_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARSIZE";
  attribute X_INTERFACE_INFO of sb_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARBURST";
  attribute X_INTERFACE_INFO of sb_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARLOCK";
  attribute X_INTERFACE_INFO of sb_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARCACHE";
  attribute X_INTERFACE_INFO of sb_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARPROT";
  attribute X_INTERFACE_INFO of sb_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 sb_axi ARQOS";
  attribute X_INTERFACE_INFO of sb_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 sb_axi RVALID";
  attribute X_INTERFACE_INFO of sb_axi_rready : signal is "xilinx.com:interface:aximm:1.0 sb_axi RREADY";
  attribute X_INTERFACE_INFO of sb_axi_rid : signal is "xilinx.com:interface:aximm:1.0 sb_axi RID";
  attribute X_INTERFACE_INFO of sb_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 sb_axi RDATA";
  attribute X_INTERFACE_INFO of sb_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 sb_axi RRESP";
  attribute X_INTERFACE_INFO of sb_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 sb_axi RLAST";
  attribute X_INTERFACE_INFO of dmi_hard_reset : signal is "xilinx.com:signal:reset:1.0 dmi_hard_reset RST";
  attribute X_INTERFACE_MODE of dmi_hard_reset : signal is "slave";
  attribute X_INTERFACE_PARAMETER of dmi_hard_reset : signal is "XIL_INTERFACENAME dmi_hard_reset, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "swerv_wrapper_verilog,Vivado 2024.2";
begin
end;
