set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0_in_context.xdc id:1 order:EARLY scoped_inst:swervolf/BD_i/swerv_wrapper_verilog_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0_in_context.xdc id:2 order:EARLY scoped_inst:swervolf/BD_i/intcon_wrapper_bd_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0_in_context.xdc id:3 order:EARLY scoped_inst:swervolf/BD_i/gpio_wrapper_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0_in_context.xdc id:4 order:EARLY scoped_inst:swervolf/BD_i/syscon_wrapper_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0_in_context.xdc id:5 order:EARLY scoped_inst:swervolf/BD_i/bootrom_wrapper_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0/BD_bidirec_0_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0/BD_bidirec_0_0_in_context.xdc id:6 order:EARLY scoped_inst:swervolf/BD_i/bidirec_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1/BD_bidirec_0_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1/BD_bidirec_0_1_in_context.xdc id:7 order:EARLY scoped_inst:swervolf/BD_i/bidirec_1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2/BD_bidirec_0_2_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2/BD_bidirec_0_2_in_context.xdc id:8 order:EARLY scoped_inst:swervolf/BD_i/bidirec_2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_0/BD_bidirec_1_0/BD_bidirec_1_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_0/BD_bidirec_1_0/BD_bidirec_1_0_in_context.xdc id:9 order:EARLY scoped_inst:swervolf/BD_i/bidirec_3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_3/BD_bidirec_0_3/BD_bidirec_0_3_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_3/BD_bidirec_0_3/BD_bidirec_0_3_in_context.xdc id:10 order:EARLY scoped_inst:swervolf/BD_i/bidirec_4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_1/BD_bidirec_1_1/BD_bidirec_1_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_1/BD_bidirec_1_1/BD_bidirec_1_1_in_context.xdc id:11 order:EARLY scoped_inst:swervolf/BD_i/bidirec_5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0/BD_bidirec_2_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0/BD_bidirec_2_0_in_context.xdc id:12 order:EARLY scoped_inst:swervolf/BD_i/bidirec_6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_3_0/BD_bidirec_3_0/BD_bidirec_3_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_3_0/BD_bidirec_3_0/BD_bidirec_3_0_in_context.xdc id:13 order:EARLY scoped_inst:swervolf/BD_i/bidirec_7} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_4/BD_bidirec_0_4/BD_bidirec_0_4_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_4/BD_bidirec_0_4/BD_bidirec_0_4_in_context.xdc id:14 order:EARLY scoped_inst:swervolf/BD_i/bidirec_8} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_2/BD_bidirec_1_2/BD_bidirec_1_2_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_2/BD_bidirec_1_2/BD_bidirec_1_2_in_context.xdc id:15 order:EARLY scoped_inst:swervolf/BD_i/bidirec_9} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_2_1/BD_bidirec_2_1/BD_bidirec_2_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_2_1/BD_bidirec_2_1/BD_bidirec_2_1_in_context.xdc id:16 order:EARLY scoped_inst:swervolf/BD_i/bidirec_10} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_3_1/BD_bidirec_3_1/BD_bidirec_3_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_3_1/BD_bidirec_3_1/BD_bidirec_3_1_in_context.xdc id:17 order:EARLY scoped_inst:swervolf/BD_i/bidirec_11} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_4_0/BD_bidirec_4_0/BD_bidirec_4_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_4_0/BD_bidirec_4_0/BD_bidirec_4_0_in_context.xdc id:18 order:EARLY scoped_inst:swervolf/BD_i/bidirec_12} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_5_0/BD_bidirec_5_0/BD_bidirec_5_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_5_0/BD_bidirec_5_0/BD_bidirec_5_0_in_context.xdc id:19 order:EARLY scoped_inst:swervolf/BD_i/bidirec_13} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_6_0/BD_bidirec_6_0/BD_bidirec_6_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_6_0/BD_bidirec_6_0/BD_bidirec_6_0_in_context.xdc id:20 order:EARLY scoped_inst:swervolf/BD_i/bidirec_14} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_7_0/BD_bidirec_7_0/BD_bidirec_7_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_7_0/BD_bidirec_7_0/BD_bidirec_7_0_in_context.xdc id:21 order:EARLY scoped_inst:swervolf/BD_i/bidirec_15} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_5/BD_bidirec_0_5/BD_bidirec_0_5_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_0_5/BD_bidirec_0_5/BD_bidirec_0_5_in_context.xdc id:22 order:EARLY scoped_inst:swervolf/BD_i/bidirec_16} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_3/BD_bidirec_1_3/BD_bidirec_1_3_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_1_3/BD_bidirec_1_3/BD_bidirec_1_3_in_context.xdc id:23 order:EARLY scoped_inst:swervolf/BD_i/bidirec_17} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_10_0/BD_bidirec_10_0/BD_bidirec_10_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_10_0/BD_bidirec_10_0/BD_bidirec_10_0_in_context.xdc id:24 order:EARLY scoped_inst:swervolf/BD_i/bidirec_18} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_11_0/BD_bidirec_11_0/BD_bidirec_11_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_11_0/BD_bidirec_11_0/BD_bidirec_11_0_in_context.xdc id:25 order:EARLY scoped_inst:swervolf/BD_i/bidirec_19} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_12_0/BD_bidirec_12_0/BD_bidirec_12_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_12_0/BD_bidirec_12_0/BD_bidirec_12_0_in_context.xdc id:26 order:EARLY scoped_inst:swervolf/BD_i/bidirec_20} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_13_0/BD_bidirec_13_0/BD_bidirec_13_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_13_0/BD_bidirec_13_0/BD_bidirec_13_0_in_context.xdc id:27 order:EARLY scoped_inst:swervolf/BD_i/bidirec_21} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_14_0/BD_bidirec_14_0/BD_bidirec_14_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_14_0/BD_bidirec_14_0/BD_bidirec_14_0_in_context.xdc id:28 order:EARLY scoped_inst:swervolf/BD_i/bidirec_22} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_15_0/BD_bidirec_15_0/BD_bidirec_15_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_15_0/BD_bidirec_15_0/BD_bidirec_15_0_in_context.xdc id:29 order:EARLY scoped_inst:swervolf/BD_i/bidirec_23} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_2_2/BD_bidirec_2_2/BD_bidirec_2_2_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_2_2/BD_bidirec_2_2/BD_bidirec_2_2_in_context.xdc id:30 order:EARLY scoped_inst:swervolf/BD_i/bidirec_24} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_3_2/BD_bidirec_3_2/BD_bidirec_3_2_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_3_2/BD_bidirec_3_2/BD_bidirec_3_2_in_context.xdc id:31 order:EARLY scoped_inst:swervolf/BD_i/bidirec_25} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_4_1/BD_bidirec_4_1/BD_bidirec_4_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_4_1/BD_bidirec_4_1/BD_bidirec_4_1_in_context.xdc id:32 order:EARLY scoped_inst:swervolf/BD_i/bidirec_26} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_5_1/BD_bidirec_5_1/BD_bidirec_5_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_5_1/BD_bidirec_5_1/BD_bidirec_5_1_in_context.xdc id:33 order:EARLY scoped_inst:swervolf/BD_i/bidirec_27} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_6_1/BD_bidirec_6_1/BD_bidirec_6_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_6_1/BD_bidirec_6_1/BD_bidirec_6_1_in_context.xdc id:34 order:EARLY scoped_inst:swervolf/BD_i/bidirec_28} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_7_1/BD_bidirec_7_1/BD_bidirec_7_1_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_7_1/BD_bidirec_7_1/BD_bidirec_7_1_in_context.xdc id:35 order:EARLY scoped_inst:swervolf/BD_i/bidirec_29} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_8_0/BD_bidirec_8_0/BD_bidirec_8_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_8_0/BD_bidirec_8_0/BD_bidirec_8_0_in_context.xdc id:36 order:EARLY scoped_inst:swervolf/BD_i/bidirec_30} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_9_0/BD_bidirec_9_0/BD_bidirec_9_0_in_context.xdc rfile:../../../../../Lab1.srcs/sources_1/bd/BD/ip/BD_bidirec_9_0/BD_bidirec_9_0/BD_bidirec_9_0_in_context.xdc id:37 order:EARLY scoped_inst:swervolf/BD_i/bidirec_31} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/constrs_1/imports/src/liteDRAM.xdc rfile:../../../../../Lab1.srcs/constrs_1/imports/src/liteDRAM.xdc id:38} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.srcs/constrs_1/imports/src/rvfpga.xdc rfile:../../../../../Lab1.srcs/constrs_1/imports/src/rvfpga.xdc id:39} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ayman/ml-rvfpga-soc/Courses/RVfpgaSoC/Labs/LabSolution/Lab1/Lab1.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:40} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/swerv_wrapper_verilog_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/intcon_wrapper_bd_0]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/gpio_wrapper_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/syscon_wrapper_0]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bootrom_wrapper_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_0]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_1]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_2]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_3]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_4]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_5]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_6]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_7]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_8]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_9]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_10]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_11]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_12]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_13]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_14]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_15]
set_property src_info {type:SCOPED_XDC file:22 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_16]
set_property src_info {type:SCOPED_XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_17]
set_property src_info {type:SCOPED_XDC file:24 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_18]
set_property src_info {type:SCOPED_XDC file:25 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_19]
set_property src_info {type:SCOPED_XDC file:26 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_20]
set_property src_info {type:SCOPED_XDC file:27 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_21]
set_property src_info {type:SCOPED_XDC file:28 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_22]
set_property src_info {type:SCOPED_XDC file:29 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_23]
set_property src_info {type:SCOPED_XDC file:30 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_24]
set_property src_info {type:SCOPED_XDC file:31 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_25]
set_property src_info {type:SCOPED_XDC file:32 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_26]
set_property src_info {type:SCOPED_XDC file:33 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_27]
set_property src_info {type:SCOPED_XDC file:34 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_28]
set_property src_info {type:SCOPED_XDC file:35 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_29]
set_property src_info {type:SCOPED_XDC file:36 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_30]
set_property src_info {type:SCOPED_XDC file:37 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells swervolf/BD_i/bidirec_31]
set_property src_info {type:XDC file:38 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[0]}]
set_property src_info {type:XDC file:38 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[0]}]
set_property src_info {type:XDC file:38 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[1]}]
set_property src_info {type:XDC file:38 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[1]}]
set_property src_info {type:XDC file:38 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[2]}]
set_property src_info {type:XDC file:38 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[2]}]
set_property src_info {type:XDC file:38 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[3]}]
set_property src_info {type:XDC file:38 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[3]}]
set_property src_info {type:XDC file:38 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[4]}]
set_property src_info {type:XDC file:38 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[4]}]
set_property src_info {type:XDC file:38 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[5]}]
set_property src_info {type:XDC file:38 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[5]}]
set_property src_info {type:XDC file:38 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[6]}]
set_property src_info {type:XDC file:38 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[6]}]
set_property src_info {type:XDC file:38 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[7]}]
set_property src_info {type:XDC file:38 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[7]}]
set_property src_info {type:XDC file:38 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[8]}]
set_property src_info {type:XDC file:38 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[8]}]
set_property src_info {type:XDC file:38 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[9]}]
set_property src_info {type:XDC file:38 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[9]}]
set_property src_info {type:XDC file:38 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[10]}]
set_property src_info {type:XDC file:38 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[10]}]
set_property src_info {type:XDC file:38 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[11]}]
set_property src_info {type:XDC file:38 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[11]}]
set_property src_info {type:XDC file:38 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_a[12]}]
set_property src_info {type:XDC file:38 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_a[12]}]
set_property src_info {type:XDC file:38 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_ba[0]}]
set_property src_info {type:XDC file:38 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_ba[0]}]
set_property src_info {type:XDC file:38 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_ba[1]}]
set_property src_info {type:XDC file:38 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_ba[1]}]
set_property src_info {type:XDC file:38 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_ba[2]}]
set_property src_info {type:XDC file:38 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_ba[2]}]
set_property src_info {type:XDC file:38 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_ras_n]
set_property src_info {type:XDC file:38 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddram_ras_n]
set_property src_info {type:XDC file:38 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_cas_n]
set_property src_info {type:XDC file:38 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddram_cas_n]
set_property src_info {type:XDC file:38 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_we_n]
set_property src_info {type:XDC file:38 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddram_we_n]
set_property src_info {type:XDC file:38 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dm[0]}]
set_property src_info {type:XDC file:38 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dm[0]}]
set_property src_info {type:XDC file:38 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dm[1]}]
set_property src_info {type:XDC file:38 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dm[1]}]
set_property src_info {type:XDC file:38 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[0]}]
set_property src_info {type:XDC file:38 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[0]}]
set_property src_info {type:XDC file:38 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[0]}]
set_property src_info {type:XDC file:38 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[1]}]
set_property src_info {type:XDC file:38 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[1]}]
set_property src_info {type:XDC file:38 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[1]}]
set_property src_info {type:XDC file:38 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[2]}]
set_property src_info {type:XDC file:38 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[2]}]
set_property src_info {type:XDC file:38 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[2]}]
set_property src_info {type:XDC file:38 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[3]}]
set_property src_info {type:XDC file:38 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[3]}]
set_property src_info {type:XDC file:38 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[3]}]
set_property src_info {type:XDC file:38 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[4]}]
set_property src_info {type:XDC file:38 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[4]}]
set_property src_info {type:XDC file:38 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[4]}]
set_property src_info {type:XDC file:38 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[5]}]
set_property src_info {type:XDC file:38 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[5]}]
set_property src_info {type:XDC file:38 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[5]}]
set_property src_info {type:XDC file:38 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[6]}]
set_property src_info {type:XDC file:38 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[6]}]
set_property src_info {type:XDC file:38 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[6]}]
set_property src_info {type:XDC file:38 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[7]}]
set_property src_info {type:XDC file:38 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[7]}]
set_property src_info {type:XDC file:38 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[7]}]
set_property src_info {type:XDC file:38 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[8]}]
set_property src_info {type:XDC file:38 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[8]}]
set_property src_info {type:XDC file:38 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[8]}]
set_property src_info {type:XDC file:38 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[9]}]
set_property src_info {type:XDC file:38 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[9]}]
set_property src_info {type:XDC file:38 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[9]}]
set_property src_info {type:XDC file:38 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[10]}]
set_property src_info {type:XDC file:38 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[10]}]
set_property src_info {type:XDC file:38 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[10]}]
set_property src_info {type:XDC file:38 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[11]}]
set_property src_info {type:XDC file:38 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[11]}]
set_property src_info {type:XDC file:38 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[11]}]
set_property src_info {type:XDC file:38 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[12]}]
set_property src_info {type:XDC file:38 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[12]}]
set_property src_info {type:XDC file:38 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[12]}]
set_property src_info {type:XDC file:38 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[13]}]
set_property src_info {type:XDC file:38 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[13]}]
set_property src_info {type:XDC file:38 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[13]}]
set_property src_info {type:XDC file:38 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[14]}]
set_property src_info {type:XDC file:38 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[14]}]
set_property src_info {type:XDC file:38 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[14]}]
set_property src_info {type:XDC file:38 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dq[15]}]
set_property src_info {type:XDC file:38 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports {ddram_dq[15]}]
set_property src_info {type:XDC file:38 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddram_dq[15]}]
set_property src_info {type:XDC file:38 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dqs_p[0]}]
set_property src_info {type:XDC file:38 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddram_dqs_p[0]}]
set_property src_info {type:XDC file:38 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dqs_p[1]}]
set_property src_info {type:XDC file:38 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddram_dqs_p[1]}]
set_property src_info {type:XDC file:38 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dqs_n[0]}]
set_property src_info {type:XDC file:38 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddram_dqs_n[0]}]
set_property src_info {type:XDC file:38 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddram_dqs_n[1]}]
set_property src_info {type:XDC file:38 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddram_dqs_n[1]}]
set_property src_info {type:XDC file:38 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_clk_p]
set_property src_info {type:XDC file:38 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports ddram_clk_p]
set_property src_info {type:XDC file:38 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_clk_n]
set_property src_info {type:XDC file:38 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports ddram_clk_n]
set_property src_info {type:XDC file:38 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_cke]
set_property src_info {type:XDC file:38 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddram_cke]
set_property src_info {type:XDC file:38 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_odt]
set_property src_info {type:XDC file:38 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddram_odt]
set_property src_info {type:XDC file:38 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddram_cs_n]
set_property src_info {type:XDC file:38 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL18_II [get_ports ddram_cs_n]
set_property src_info {type:XDC file:38 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets ddr2/ldc/regs0]
set_property src_info {type:XDC file:38 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list ddr2/ldc/FDPE/PRE ddr2/ldc/FDPE_1/PRE ddr2/ldc/FDPE_2/PRE ddr2/ldc/FDPE_3/PRE ddr2/ldc/FDPE_4/PRE ddr2/ldc/FDPE_5/PRE ddr2/ldc/FDPE_6/PRE ddr2/ldc/FDPE_7/PRE]]
set_property src_info {type:XDC file:38 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins [list ddr2/ldc/FDPE/C ddr2/ldc/FDPE_2/C ddr2/ldc/FDPE_4/C ddr2/ldc/FDPE_6/C]] -to [get_pins [list ddr2/ldc/FDPE_1/D ddr2/ldc/FDPE_3/D ddr2/ldc/FDPE_5/D ddr2/ldc/FDPE_7/D]] 2.000
set_property src_info {type:XDC file:39 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:XDC file:39 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck_dmi -add [get_pins tap/tap_dmi/TCK]
set_property src_info {type:XDC file:39 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck_dtmcs -add [get_pins tap/tap_dtmcs/TCK]
set_property src_info {type:XDC file:39 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck_idcode -add [get_pins tap/tap_idcode/DRCK]
set_property src_info {type:XDC file:39 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -regexp {tap/dtmcs_r_reg\[([2-9]|[1-9][0-9])\]}]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name subfragments_pll_fb -source [get_pins ddr2/ldc/PLLE2_ADV/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins ddr2/ldc/PLLE2_ADV/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkout0 -source [get_pins ddr2/ldc/PLLE2_ADV/CLKIN1] -multiply_by 2 -add -master_clock [get_clocks sys_clk_pin] [get_pins ddr2/ldc/PLLE2_ADV/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkout1 -source [get_pins ddr2/ldc/PLLE2_ADV/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins ddr2/ldc/PLLE2_ADV/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkout2 -source [get_pins ddr2/ldc/PLLE2_ADV/CLKIN1] -multiply_by 2 -add -master_clock [get_clocks sys_clk_pin] [get_pins ddr2/ldc/PLLE2_ADV/CLKOUT2]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkout3 -source [get_pins ddr2/ldc/PLLE2_ADV/CLKIN1] -edges {1 2 3} -edge_shift {1.250 -1.250 -3.750} -add -master_clock [get_clocks sys_clk_pin] [get_pins ddr2/ldc/PLLE2_ADV/CLKOUT3]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfb -source [get_pins clk_gen/PLLE2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clkout1] [get_pins clk_gen/PLLE2_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_core -source [get_pins clk_gen/PLLE2_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} -add -master_clock [get_clocks clkout1] [get_pins clk_gen/PLLE2_BASE_inst/CLKOUT0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/swerv_wrapper_verilog_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/intcon_wrapper_bd_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/gpio_wrapper_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/syscon_wrapper_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bootrom_wrapper_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_4]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_5]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_6]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_7]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_8]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_9]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_11]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_12]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_13]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_14]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_15]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_16]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_17]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_18]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_19]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_20]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_21]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_22]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_23]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_24]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_25]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_26]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_27]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_28]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_29]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_30]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells swervolf/BD_i/bidirec_31]
